name: Project-testing-selenium

on:
  push:
    branches: [ "develop", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Verify Java
        run: |
          java -version
          mvn -version
          firefox --version

      - name: Build with Maven
        run: mvn clean test
        
      - name: Upload Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: cucumber-report
         path: target/cucumber-reports.html
      